# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikto_b/Documents/C++/fantastic-train

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikto_b/Documents/C++/fantastic-train

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikto_b/Documents/C++/fantastic-train/CMakeFiles /home/nikto_b/Documents/C++/fantastic-train/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikto_b/Documents/C++/fantastic-train/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Src/bases.o: Src/bases.cpp.o

.PHONY : Src/bases.o

# target to build an object file
Src/bases.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/bases.cpp.o
.PHONY : Src/bases.cpp.o

Src/bases.i: Src/bases.cpp.i

.PHONY : Src/bases.i

# target to preprocess a source file
Src/bases.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/bases.cpp.i
.PHONY : Src/bases.cpp.i

Src/bases.s: Src/bases.cpp.s

.PHONY : Src/bases.s

# target to generate assembly for a file
Src/bases.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/bases.cpp.s
.PHONY : Src/bases.cpp.s

Src/geometry.o: Src/geometry.cpp.o

.PHONY : Src/geometry.o

# target to build an object file
Src/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/geometry.cpp.o
.PHONY : Src/geometry.cpp.o

Src/geometry.i: Src/geometry.cpp.i

.PHONY : Src/geometry.i

# target to preprocess a source file
Src/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/geometry.cpp.i
.PHONY : Src/geometry.cpp.i

Src/geometry.s: Src/geometry.cpp.s

.PHONY : Src/geometry.s

# target to generate assembly for a file
Src/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/geometry.cpp.s
.PHONY : Src/geometry.cpp.s

Src/grapher.o: Src/grapher.cpp.o

.PHONY : Src/grapher.o

# target to build an object file
Src/grapher.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/grapher.cpp.o
.PHONY : Src/grapher.cpp.o

Src/grapher.i: Src/grapher.cpp.i

.PHONY : Src/grapher.i

# target to preprocess a source file
Src/grapher.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/grapher.cpp.i
.PHONY : Src/grapher.cpp.i

Src/grapher.s: Src/grapher.cpp.s

.PHONY : Src/grapher.s

# target to generate assembly for a file
Src/grapher.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/grapher.cpp.s
.PHONY : Src/grapher.cpp.s

Src/main.o: Src/main.cpp.o

.PHONY : Src/main.o

# target to build an object file
Src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/main.cpp.o
.PHONY : Src/main.cpp.o

Src/main.i: Src/main.cpp.i

.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s

.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

Src/math.o: Src/math.cpp.o

.PHONY : Src/math.o

# target to build an object file
Src/math.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/math.cpp.o
.PHONY : Src/math.cpp.o

Src/math.i: Src/math.cpp.i

.PHONY : Src/math.i

# target to preprocess a source file
Src/math.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/math.cpp.i
.PHONY : Src/math.cpp.i

Src/math.s: Src/math.cpp.s

.PHONY : Src/math.s

# target to generate assembly for a file
Src/math.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/math.cpp.s
.PHONY : Src/math.cpp.s

Src/pathfinder.o: Src/pathfinder.cpp.o

.PHONY : Src/pathfinder.o

# target to build an object file
Src/pathfinder.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/pathfinder.cpp.o
.PHONY : Src/pathfinder.cpp.o

Src/pathfinder.i: Src/pathfinder.cpp.i

.PHONY : Src/pathfinder.i

# target to preprocess a source file
Src/pathfinder.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/pathfinder.cpp.i
.PHONY : Src/pathfinder.cpp.i

Src/pathfinder.s: Src/pathfinder.cpp.s

.PHONY : Src/pathfinder.s

# target to generate assembly for a file
Src/pathfinder.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/pathfinder.cpp.s
.PHONY : Src/pathfinder.cpp.s

Src/routines.o: Src/routines.cpp.o

.PHONY : Src/routines.o

# target to build an object file
Src/routines.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/routines.cpp.o
.PHONY : Src/routines.cpp.o

Src/routines.i: Src/routines.cpp.i

.PHONY : Src/routines.i

# target to preprocess a source file
Src/routines.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/routines.cpp.i
.PHONY : Src/routines.cpp.i

Src/routines.s: Src/routines.cpp.s

.PHONY : Src/routines.s

# target to generate assembly for a file
Src/routines.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Src/routines.cpp.s
.PHONY : Src/routines.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... Src/bases.o"
	@echo "... Src/bases.i"
	@echo "... Src/bases.s"
	@echo "... Src/geometry.o"
	@echo "... Src/geometry.i"
	@echo "... Src/geometry.s"
	@echo "... Src/grapher.o"
	@echo "... Src/grapher.i"
	@echo "... Src/grapher.s"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/math.o"
	@echo "... Src/math.i"
	@echo "... Src/math.s"
	@echo "... Src/pathfinder.o"
	@echo "... Src/pathfinder.i"
	@echo "... Src/pathfinder.s"
	@echo "... Src/routines.o"
	@echo "... Src/routines.i"
	@echo "... Src/routines.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

